### ISSUE TITLE
Remove default delete action

### ISSUE THREAD

**Issue by broakenmedia** [ernestoyaquello/DragDropSwipeRecyclerview#11]
Thanks for working on the swipe functionality. I have one further suggestion. Currently the library fires the ‘onItemSwiped’ callback and immediately removes the item from the array list. This makes it impossible to add undo/other functionality as I cannot intercept the delete.

I have pulled the library and simply deleted the ‘remove’ function call. I can then call ‘remove’ from my own app whenever I like. In my case I show a confirmation dialog in the onItemSwiped before calling remove.

**Comment by ernestoyaquello** [comment]
I will implement this feature soon, thanks for the suggestion.

**Comment by ernestoyaquello** [comment]
Implemented on version 0.1.0, please check it out.

Now, `OnItemSwipeListener.onItemSwiped()` returns a boolean. When this boolean is true, the swiped item won't be removed from the adapter's data set (it will be up to the developer to make the necessary changes to the data set).
