### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by b099l3** [ernestoyaquello/DragDropSwipeRecyclerview#19]
Hello ernestoyaquello,

It would be good if this repo had some sort of CI, so that we could see if there are any breaking changes.

Love
Yer best pal in the world
and your next of kin

**Comment by ernestoyaquello** [comment]
Hi my dear next of kin,

I appreciate your suggestion, but this is a small library and I am the only one testing and releasing new versions, so a CI isn't really needed. Besides, the [Gradle file](https://github.com/ernestoyaquello/DragDropSwipeRecyclerview/blob/develop/drag-drop-swipe-recyclerview/build.gradle) includes a script to upload the library to Bintray, which means that I can release a new version of it just by clicking a button.

Thanks for your input anyway.

Cheers,

Jim from Paisley.

**Comment by b099l3** [comment]
I think the fact that _you_ are the only one testing probably suggests that there should be unit tests or UI tests aswel?

**Comment by ernestoyaquello** [comment]
I love tests as much as the next guy, but testing this library in an automated way would be kinda difficult and not too useful. I am not saying it would be completely impossible to create some useful UI tests; I just don't think it is worth the effort in this case. In a library like this one, where there is a lot of visual stuff going on, I prefer to check that everything looks and behaves as expected by testing the sample app manually myself.

**Comment by b099l3** [comment]
Ah that must be why it takes so long for updates like the other repo

**Comment by ernestoyaquello** [comment]
The other repo was abandoned for a while, as I already mentioned there, and that's the only reason why it wasn't updated in a long time. CI is not a concern there either.
