### ISSUE TITLE
Add onListScrollStateChanged to OnListScrollListener

### ISSUE THREAD

**Issue by GhimpuLucianEduard** [ernestoyaquello/DragDropSwipeRecyclerview#20]
As far as I've seen from the code,  **onScrolled(RecyclerView recyclerView, int dx, int dy)** is used for **onListScrolled(scrollDirection: OnListScrollListener.ScrollDirection, distance: Int)**.
But **onScrollStateChanged(RecyclerView recyclerView, int newState)** is unsued.

What about adding a new method to the listener to indicate changes in the state of the scroll? I think the changes in the code would be pretty small.

This feature could be helpful in some situations.

Looking forward to feedback.

**Comment by ernestoyaquello** [comment]
I have implemented this and released a new version. Thanks for the suggestion!
