### ISSUE TITLE
Sometimes items in the Reyclerview become less opaque after dataSet changes

### ISSUE THREAD

**Issue by GhimpuLucianEduard** [ernestoyaquello/DragDropSwipeRecyclerview#21]
This happens to me when I delete items from my data source (LiveData) and then I try to update the dataSet.

`        viewModel.items.observe(this@MyFragment, Observer {
            adapter.dataSet = it
        })
`

Also if you try to move the opaque item, his opacity will become normal again.

This does **not** happen when you use the default behavior of the swipe, which as far as I've seen uses **removeItem(position: Int)**

On the other hand, when adding an item everything seems to be ok.
I'm not sure this happens. I will try to reproduce it in a smaller project asap. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20892597/56461096-af224580-63b5-11e9-9320-c943778181b3.gif)

**Comment by ernestoyaquello** [comment]
Good catch. I already have an idea of why this is happening, but a small project to reproduce the issue would be ideal, thanks!

**Comment by GhimpuLucianEduard** [comment]
Sorry it took so long, easter and stuff.

Anyway, here's a small project with the issue:
https://github.com/GhimpuLucianEduard/RecyclerViewBug

Let me know if I can help with more info. The structure and code it's quite similar to what I did in my main project (the gif is from the main project).

**Comment by ernestoyaquello** [comment]
I have released a new version of the library that should fix the issue. Thank you very much for reporting it!

**Comment by ernestoyaquello** [comment]
BTW, @GhimpuLucianEduard, I recommend you to try to synchronise the dataset of your adapter in a different way to improve the visual effects of adding, editing and removing items. For example, instead of just doing this:

```kotlin
Observer { adapter.dataSet = it }
```

You could do something like this:

```kotlin
Observer { updateDataSet(it) }

...

@Synchronized private fun updateDataSet(updatedListOfItems: List<Item>) {
    updateItemsData(updatedListOfItems)
    removeDeletedItems(updatedListOfItems)
    addNewItems(updatedListOfItems)
}

private fun updateItemsData(updatedListOfItems: List<Item>) {
    updatedListOfItems.forEach { itemWithUpdatedData ->
        val currentItem = adapter.dataSet.firstOrNull { it.id == itemWithUpdatedData.id }
        // The item properties must be bindable so the changes are reflected in the UI
        currentItem?.updateItemProperties(itemWithUpdatedData)
    }
}

private fun removeDeletedItems(updatedListOfItems: List<Item>) {
    val removedItems = adapter.dataSet.filter { currentItem ->
        !updatedListOfItems.any { it.id == currentItem.id }
    }

    removedItems.forEach {
        val itemPosition = adapter.dataSet.indexOf(it)
        if (itemPosition != -1)
            adapter.removeItem(itemPosition)
    }
}

private fun addNewItems(updatedListOfItems: List<Item>) {
    val addedItems = updatedListOfItems.filter { newItem ->
        !adapter.dataSet.any { it.id == newItem.id }
    }

    addedItems.forEach {
        val itemPosition = updatedListOfItems.indexOf(it)
        if (itemPosition != -1)
            adapter.insertItem(itemPosition, it)
    }
}
```

It is a little bit more complicated and all, but it makes the changes in the list so much smoother.
