### ISSUE TITLE
 Long left swipe, Long right swipe

### ISSUE THREAD

**Issue by biniamHaddish** [ernestoyaquello/DragDropSwipeRecyclerview#24]
It Would be helpful if you add 

Short left swipe
Long left swipe
Short right swipe
Long right swipe

functionality separately

**Comment by ernestoyaquello** [comment]
Could you please elaborate? I am not sure what you mean by "short/long" swipe. Thanks!

**Comment by biniamHaddish** [comment]
![demo](https://user-images.githubusercontent.com/10844954/58559331-8c444600-822b-11e9-8918-4a9e6f71d7a2.gif)
Swipe action like the above gif.😊

**Comment by ernestoyaquello** [comment]
Thanks again for the suggestion. I have been very busy this week, but I will try to take a look at this tomorrow. From the top of my head, I would say this is easily doable with the current API of the library, but I will double check.

**Comment by biniamHaddish** [comment]
> From the top of my head, I would say this is easily doable with the current API of the library, but I will double check.

How do you mean by that?

**Comment by ernestoyaquello** [comment]
Hi again, and sorry about the delay, I have been crazy busy lately.

Taking a look at your GIF again, I am a little bit confused about how this is supposed to work. The visual part is easy, and probably something you could somehow implement with this library already, but I am unsure about what's supposed to happen when you release the item.

If the intent here is to make the item disappear executing a different action depending on how much you have swiped it, then I am afraid that's not a feature I want to implement – not only would that go against the Material Design guidelines, but also it would provide a confusing experience for the user, in my opinion. However, if the way this is supposed to work is different than that, then I am open to consider your suggestion.

**Comment by biniamHaddish** [comment]
Hi again,
I implemented the functionality it is not perfect but I think for now it might help me or other so I made a library for it check it out and let me know if you have any suggestion about it https://github.com/biniamHaddish/SwipeView
