### ISSUE TITLE
ScrollTo, ScrollToPosition not working on this list

### ISSUE THREAD

**Issue by klaszlo8207** [ernestoyaquello/DragDropSwipeRecyclerview#25]
list.scrollTo(..)

list.scrollToPosition(..)

linearLayoutManager.scrollToPositionWithOffset(..) also not working

Can you help me how to do this?

**Comment by ernestoyaquello** [comment]
Hi! I have just tried using `linearLayoutManager.scrollToPositionWithOffset(..)` and it works perfectly. In fact, I would find it very odd if this library were somehow interfering with the scrolling feature, as there isn't anything on its implementation that could cause such function to fail or misbehave. After all, this is just an extension of `RecyclerView`, so all the features of a normal RecyclerView should still work on it.

Could you please show me the exact code you are using? Thanks!

**Comment by klaszlo8207** [comment]
scrollTo not worked
And scrollToPositionWithOffset not worked too

But scrollToPosition and after scrollBy(0, y) worked. Thanks
