### ISSUE TITLE
Question - Custom layout aniamtion

### ISSUE THREAD

**Issue by flaringapp** [ernestoyaquello/DragDropSwipeRecyclerview#29]
Does this library support layout animation? I wonder if I'll be able to set custom grid animation with   **appear delay**

**Comment by ernestoyaquello** [comment]
Hmm, to be honest, I am not entirely sure it would work fine and be compatible. Have you tried implementing it to see if it works?

**Comment by flaringapp** [comment]
@ernestoyaquello I've implemented your lib, extended from your RecyclerView class to support grid animation, set up a layoutAnimation parameter in xml and everything forks fine

**Comment by ernestoyaquello** [comment]
Glad to hear it!
