### ISSUE TITLE
Recyclerview item background color permanently set to behind_swiped_item_bg_color even if swipe position is returned to start

### ISSUE THREAD

**Issue by alvindizon** [ernestoyaquello/DragDropSwipeRecyclerview#31]
Following the basic setup described in the readme, drag, drop, and swipe works well, but I noticed that when I do not continue with swiping and return the item to its starting position or if I release the item, the item background color remains set to ```behind_swiped_item_bg_color```.

**Comment by ernestoyaquello** [comment]
Do you happen to be using a transparent or semitransparent background in your item layout? If so, I think I can try to implement a solution when I have time.

**Comment by alvindizon** [comment]
I just realized that I did not set a ```background``` for my item layout XML. Once I did, this behavior does not happen anymore. Thanks for drawing my attention to the background.

**Comment by ernestoyaquello** [comment]
I was thinking about limiting the drawing area of the background displayed behind swiped elements to avoid drawing it just behind the item layout, but that would be problematic for item layouts with round borders, transparencies, etcetera. Therefore, given you have managed to solve the issue, I think I will leave the implementation the way it is and close the issue.
