### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mparag31** [ernestoyaquello/DragDropSwipeRecyclerview#37]
Is there any way to change position only two list items (swipe only two) views. That means the the dragged one and the one where the dragged item is dropped.

**Comment by ernestoyaquello** [comment]
I am not sure I understand the question, but if you want to restrict dragging, dropping or swiping on specific items while allowing it to happen on others, you just have to override the methods `canBeDragged(...)`, `canBeDroppedOver(...)` and `canBeSwiped(...)` in your adapter.

I hope this can be of help, but please let me know if you need further clarification.
