### ISSUE TITLE
Grid issue

### ISSUE THREAD

**Issue by andypress83** [ernestoyaquello/DragDropSwipeRecyclerview#41]
Hello,
maybe I've not really gotten it but I can't create a grid view with 5 columns and 2 rows.

mList.numOfColumnsPerRowInGridList = 5 or mList.numOfRowsPerColumnInGridList = 2 don't have any effect.

Any hints are appreciated.

**Comment by ernestoyaquello** [comment]
How are you setting it up? It is not enough with doing `mList.numOfColumnsPerRowInGridList = 5`, you need to set a layout manager, the orientation, et cetera. Something like this should do the trick:

```kotlin
list = rootView.findViewById(R.id.list)
list.adapter = myAdapter
...
list.layoutManager = GridLayoutManager(activity, 5)
list.orientation = DragDropSwipeRecyclerView.ListOrientation.GRID_LIST_WITH_HORIZONTAL_SWIPING
list.numOfColumnsPerRowInGridList = 5
```

Let me know how it goes!

**Comment by andypress83** [comment]
Thanks man, I missed the GridLayoutManager....

**Comment by ernestoyaquello** [comment]
Glad to be of help! :)
