### ISSUE TITLE
How to keep one item is not able to drag & drop?

### ISSUE THREAD

**Issue by congdanh1608** [ernestoyaquello/DragDropSwipeRecyclerview#46]
I implement this library to show the grid item with drag & drop feature. I want to disable that feature for the latest item. 
Do you know any way to handle it?

Thank you.

**Comment by ernestoyaquello** [comment]
This is in the documentation, please take a look at the method `canBeDragged(...)` of the adapter. You can override it and implement it as you wish.

I hope that helps.

**Comment by congdanh1608** [comment]
Hi @ernestoyaquello 
Thanks for your help. I already tried. 
My latest item (fixed item) couldn't drag & drop. But the issue is we can drag other items (the items I allow to drag & drop) and drop them to the fixed item. 
=> the fixed item was changed position.

Do you have any ideas? 
Thank you.
