### ISSUE TITLE
Item Click not working if whole item view passed into getViewToTouchToStartDraggingItem()

### ISSUE THREAD

**Issue by Hassaan68** [ernestoyaquello/DragDropSwipeRecyclerview#49]
Item Click not working if whole item view passed into getViewToTouchToStartDraggingItem() for drag view. if there is not drag icon and whole view used for click as well as drag at the same time then item click listener will not be called.

**Comment by AbdElraoufSabri** [comment]
#Workaround

1. just create a drag view i.e ImageView and set it as the drag view using `getViewToTouchToStartDraggingItem`
1. set the image view visibility as gone.

If you set a click listener to the view it'll be called.
Hence you'll disable dragging

**Comment by ernestoyaquello** [comment]
Please read the documentation. If you want the whole item view to be used for dragging, the method `getViewToTouchToStartDraggingItem()` should return null.
