### ISSUE TITLE
Swipe only one Direction and DiffUtil

### ISSUE THREAD

**Issue by ueen** [ernestoyaquello/DragDropSwipeRecyclerview#50]
Hey, is it possible only to allow swiping in one direction (primary or secondary)? Possibly they could be renamed to Left/Right or Start/End to follow convention?
Also it would be great if the Adapter would feature the DiffUtil ListAdapter for nice animations :)

**Comment by ernestoyaquello** [comment]
It is already possible to allow swiping in one direction only, please take a look at the method `disableSwipeDirection()`. Regarding the usage of `DiffUtil`, I would add it in the next version of the library.

Thanks for your input!

**Comment by ernestoyaquello** [comment]
I have implemented the ability to use `DiffUtil` if preferred, please take a look at the [documentation about it](https://github.com/ernestoyaquello/DragDropSwipeRecyclerview#implementing-diffutil). This feature is available in the version [`1.0.0`](https://github.com/ernestoyaquello/DragDropSwipeRecyclerview/releases/tag/v1.0.0) of the library.

I hope that helps!
