### ISSUE TITLE
Swipe background color corner radius

### ISSUE THREAD

**Issue by amatkivskiy** [ernestoyaquello/DragDropSwipeRecyclerview#51]
Hi @ernestoyaquello 
First of all thanks a lot for this wonderful library 👍 

I've just started using it so I might miss something but I am using **MaterialCardView** for the list item layout - swipe background comes without corner radius on it 😞 

It can be easily demonstrated in your sample app if you set the corner radius to `20dp`  (in `list_item_vertical_list_cardview.xml`) for example. 
I've made a quick demo video on this: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3864884/102531520-1886ba00-40ab-11eb-9195-661c28e20d1d.gif)

In my code, I need to set the corner radius to `0dp` to avoid such an issue 😞 
Can you please help with this?

**Comment by ernestoyaquello** [comment]
There are two ways to set a background that will appear when you swipe an item:

1. You define a colour and an icon and let the library draw the background for you (for this, you need to set properties such as `behindSwipedItemBackgroundColor`, `behindSwipedItemIconDrawableId`, `behindSwipedItemIconMargin`, etc).
2. You define a custom layout that will be used as the background (by setting properties such as `behindSwipedItemLayoutId` and `behindSwipedItemSecondaryLayoutId`).

When using a `CardView`, just use a custom layout with whatever corner radius you want. Take a look at the layout `behind_swiped_grid_list.xml` of the sample project if you want a reference.

I hope that helps!

**Comment by amatkivskiy** [comment]
Thanks @ernestoyaquello I will try later 👍
