### ISSUE TITLE
[Features] Firestore/Firebase support

### ISSUE THREAD

**Issue by forceporquillo** [ernestoyaquello/DragDropSwipeRecyclerview#55]
Hi @ernestoyaquello,

I'm trying to integrate this with some workaround implementation of firestore adapter from Firebase UI samples. However, it gives me an error throwing out of bounds exception (since I cannot access the internal code of your library). It would be nice to have a firebase or firestore adapter support.

PS.  I want to mention that I'm having fun using your library, thanks for your awesome work!

**Comment by ernestoyaquello** [comment]
Thing is, for convenience, the adapter of this library is loaded with code aimed at making the overall use of it easier. Unfortunately, that means that you cannot use it along with other adapters that have their own logic. And while I would like to move most of that code out of the base adapter (for example, to a config class), I am afraid that parts of it need to stay in the adapter, so I cannot really make the library compatible with the Firebase adapter.

In any case, feel free to copy the code of the library manually into your extension of the Firebase adapter. Although I haven't tried it myself, I reckon that it should work.

Thanks for your words, and good luck with this!
