### ISSUE TITLE
No Java example.

### ISSUE THREAD

**Issue by fourofspades** [ernestoyaquello/DragDropSwipeRecyclerview#56]
Spent a long time trying to devode the Kotlin example to work in Java, and still having troubles.  At this point, i'm not sure if it's me, or it simply isn't compatible.    A Java example would be useful.

**Comment by fourofspades** [comment]
Found a Java project on Github using this.

https://github.com/harrowmykel/Intelligent-Notes-App/

Also found my problem, I wasn't passing the list into the superclass on construction.

**Comment by ernestoyaquello** [comment]
Glad to see you managed to solve it!

**Comment by JonathanNet** [comment]
> https://github.com/harrowmykel/Intelligent-Notes-App/

Hi do you have the source from that github?, because I dosnt work anymore, and I need some java code for this :)
