### ISSUE TITLE
Can I use DragDropSwipeRecyclerview in conjunction with LiveData in the room?

### ISSUE THREAD

**Issue by WORLD8848** [ernestoyaquello/DragDropSwipeRecyclerview#58]
Can I use DragDropSwipeRecyclerview in conjunction with LiveData in the room?

I'm inquiring because DataSet is in List format.

**Comment by ernestoyaquello** [comment]
Yes, you can, that's what I do in one of my own apps. It doesn't matter that the dataset is a list, all you have to do is update the items when necessary.

For example, this is one way to do it:

```kotlin
// In your view, observe the LiveData property of your viewmodel that contains the items
viewModel.items.observe(viewLifecycleOwner, { items -> onItemsUpdated(items) })

private fun onItemsChanged(items: List<Item>?) {
    // This setter will take care of notifying about the changes
    itemsAdapter.dataSet = items
}
```

You can also use other methods of the adapter such as `addItem()`, `removeItem()`, etc. And if you want to use `DiffUtil` to be able to replace the entire list of items while ensuring that the correct animations are always run, then extend the class `DragDropSwipeDiffCallback` and override the method `createDiffUtil()` of the adapter to make it return an instance of your implementation.

I hope that helps!

**Comment by WORLD8848** [comment]
I applied the sample code above.
Thank you for being able to use it.

You said you tried applying the source to your app. I would appreciate it if you could introduce the app.
