### ISSUE TITLE
Example between recycler view vertically?

### ISSUE THREAD

**Issue by felipe9962** [ernestoyaquello/DragDropSwipeRecyclerview#60]
I am trying to move an item from one recyclerview to another vertically but I can't do it and I don't see any example, any idea?

**Comment by ernestoyaquello** [comment]
From the top of my head, I am not sure about how to do this, or whether it is possible to do with this library. It sounds like an interesting challenge, so I will take a look when I have time.

**Comment by youarenot667543** [comment]
![Screenshot_٢٠٢٢٠١٠٨-١٣٣١٤٣_Nova7.jpg](https://user-images.githubusercontent.com/92665957/148662910-d1309354-ec4d-44b7-b574-c588685f572c.jpg)

**Comment by ernestoyaquello** [comment]
I took a look, and I couldn't find a nice, non-hacky way of getting this to work with this library. The library already supports a lot of functionality, so I am not sure I want to burden myself with trying to support such a complex feature on top of everything else.

Sorry about that, and thanks for the suggestion! If you end up finding a nice way to get this done, feel free to create a PR. 👍
