### ISSUE TITLE
[QUESTION]: Can we stop the drag at some point and make a button?

### ISSUE THREAD

**Issue by Drjacky** [ernestoyaquello/DragDropSwipeRecyclerview#61]
Can we stop the drag at some point and when the user releases the dragging, there will be a button, and then, after clicking on the button, the action invokes?

**Comment by ernestoyaquello** [comment]
I think you should be able to do it. For example, the callback `onDragFinished(item: T, viewHolder: U)` could be implemented to show or hide a button, if that's what you want.

I will close the issue for now, but if I am missing something or you have extra implementation details that are relevant, please let me know!
