### ISSUE TITLE
missing getBindingAdapterPosition()

### ISSUE THREAD

**Issue by fourofspades** [ernestoyaquello/DragDropSwipeRecyclerview#64]
Confused, this seems to extend RecyclerView 1.2x, but it's missing getBindingAdapterPosition()

**Comment by ernestoyaquello** [comment]
The latest code in `master` hasn't made it to a release yet, but I will publish one soon.

**Comment by ernestoyaquello** [comment]
A [new version](https://github.com/ernestoyaquello/DragDropSwipeRecyclerview/releases/tag/v1.1.0) of the library has been released. Now, `getBindingAdapterPosition()` will be available. I hope it helps!

**Comment by fourofspades** [comment]
Thanks, new version is working well.   I am using this to highlight a selected item, using this pattern:

https://stackoverflow.com/a/30046476/14421174

I'm having trouble updating the selected item, if the drag and drop affects the order of the currently selected item.  Is there any advice on how to solve this?

**Comment by ernestoyaquello** [comment]
If the position of the selected item has changed after the dragging, you will need to update the value of the private property `selectedPos` accordingly. Then, you will need to notify the change on the old position and in the new one for the bindings on those positions of the list to fire again.

However, I would recommend that you don't store your selected item in dynamic memory using its position, but rather its ID. And if your items don't have a unique ID, maybe you can just store the entire selected item?

**Comment by fourofspades** [comment]
Thanks for the suggestion, I switched to using unique IDs and doing string comparison of name it made things alot simpler!
