### ISSUE TITLE
Disable Swipe 

### ISSUE THREAD

**Issue by khalil05400** [ernestoyaquello/DragDropSwipeRecyclerview#68]
I want to disable swipe on some screen programmatically?unable to do this

**Comment by ernestoyaquello** [comment]
As @WORLD8848 has explained, you can disable swiping for each individual item overriding the adapter method `canBeSwiped`. Furthermore, if you want to disable swiping for just one direction, please check out the recycler view method called `disableSwipeDirection`. You can find information about it all in the [readme file](https://github.com/ernestoyaquello/DragDropSwipeRecyclerview#readme).
