### ISSUE TITLE
can we use this library in java code?

### ISSUE THREAD

**Issue by ArslanKathia** [ernestoyaquello/DragDropSwipeRecyclerview#8]

**Comment by ernestoyaquello** [comment]
Yes, `Kotlin` code can be used from `Java`, please [take a look here at the official documentation](https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html).

For example, if you want to set a custom layout to be displayed behind swiped items, in `Kotlin` you do it like this:

```kotlin
mList.behindSwipedItemLayoutId = R.layout.your_custom_layout
```

And in `Java`, you do it this way:

```kotlin
mList.setBehindSwipedItemLayoutId(R.layout.your_custom_layout);
```

As you can see, the code is almost identical.

I hope this helps, but please let me know if you have any problems!
